Global e2e tests refactoring and improvement
AdTechMedia/adtechmedia-website pull request #283
Opened 2017-07-18 14:51 UTC by avozicov

- Implemented POMs for:
   - api-page
   - contact-page
   - demo-modal
   - footer
   - header
   - home-page
   - quick-links
   - social-links
- Refactored all tests scripts to use page objects described in "pages" directory 
- Added new script for "Social Links" validation
- Added new script for "API page" content assert 
- Fixed const names to provide more context of selectors and actions

2017-07-18 15:11 UTC, AlexanderC requested changes

2017-07-18 15:11 UTC, AlexanderC commented on test/e2e/tests/assertApiPage.e2e.js
> +  .page`https://www-stage.adtechmedia.io/api/`;
use base host (e.g. `https://www-stage.adtechmedia.io`) from a `config.js` like this: `config.www_base_host`

```javascript
// config.js

export default {
  www_base_host: process.env.WWW_BASE_HOST || 'https://www-test.adtechmedia.io',
}
```

You can run tests like `WWW_BASE_HOST='https://www-stage.adtechmedia.io' recink run e2e`

2017-07-18 15:11 UTC, AlexanderC commented on test/e2e/tests/assertFooter.e2e.js
> +    .resizeWindow(1920, 1080)
Try setting default window size from config (see nighmare docs)

2017-07-18 15:11 UTC, AlexanderC commented on test/e2e/tests/submitDemoRequest.e2e.js
> +    .typeText(requestDemoForm.demoFormEmailField, 'hellfire@yahoo.com')
Please use http://chancejs.com library for generating random test data

2017-07-18 15:11 UTC, AlexanderC commented on test/e2e/tests/submitDemoRequest.e2e.js
> +    .expect(Selector(requestDemoForm.demoFormResponseText).innerText).eql('\nThank you for the interest in AdTechMedia WordPress Plugin\nPlease check your inbox to schedule your demo.\n');
use `.contains` instead of `. eql` to avoid spaces matching

2017-07-19 08:07 UTC, avozicov commented on test/e2e/tests/submitDemoRequest.e2e.js
> +    .expect(Selector(requestDemoForm.demoFormResponseText).innerText).eql('\nThank you for the interest in AdTechMedia WordPress Plugin\nPlease check your inbox to schedule your demo.\n');
I got it, thank you.

_Latest Status:_ Fixed

2017-07-19 08:47 UTC, avozicov commented on test/e2e/tests/assertApiPage.e2e.js
> +  .page`https://www-stage.adtechmedia.io/api/`;
I got it, thank you.

Latest Status: Fixed

2017-07-19 18:33 UTC, avozicov commented on test/e2e/tests/assertFooter.e2e.js
> +    .resizeWindow(1920, 1080)
I got it, thank you.

Latest status: Fixed

2017-07-20 12:40 UTC, avozicov commented on test/e2e/tests/submitDemoRequest.e2e.js
> +    .typeText(requestDemoForm.demoFormEmailField, 'hellfire@yahoo.com')
I got it, thank you.

Latest status: Fixed

2017-07-20 13:00 UTC, AlexanderC approved these changes

2017-07-20 13:01 UTC, AlexanderC commented
Please update recink.yml from project root to use the tests and dependencies

2017-07-20 13:01 UTC, merged