Added mobile resolution scripts | Removed hardcoded url to use DEPLOY_HOST | Added pom selector for mobile
AdTechMedia/adtechmedia-website pull request #300
Opened 2017-07-28 16:24 UTC by avozicov

2017-07-28 16:55 UTC, grigoreme requested changes

2017-07-28 16:55 UTC, grigoreme commented on test/e2e/tests/mobile/assert-mobile-menu.e2e.js
> +    await t
Please use empty line between functions

2017-07-28 16:55 UTC, grigoreme commented on test/e2e/tests/mobile/assert-mobile-menu.e2e.js
> +    await t
same

2017-07-28 16:55 UTC, grigoreme commented on test/e2e/tests/mobile/assert-mobile-menu.e2e.js
> +    await t
same

2017-07-28 16:55 UTC, grigoreme commented on test/e2e/tests/mobile/assert-mobile-menu.e2e.js
> +    await t
same

2017-07-28 16:55 UTC, grigoreme commented on test/e2e/tests/mobile/mobile-request-demo.e2e.js
>      .expect(Selector(requestDemoModal.responseText).innerText).contains('\nThank you for the interest in AdTechMedia WordPress Plugin\nPlease check your inbox to schedule your demo.\n');
Get rid of that big line, you can split into new lines by functions like:
```
expect(
  Selector(requestDemoModal.responseText).innerText)
  .contains('\nThank you for the interest in AdTechMedia WordPress Plugin\nPlease check your inbox to schedule your demo.\n');```

2017-07-31 09:05 UTC, avozicov commented on test/e2e/tests/mobile/assert-mobile-menu.e2e.js
> +    await t
got it, thank you.
Fixed.

2017-07-31 09:05 UTC, avozicov commented on test/e2e/tests/mobile/mobile-request-demo.e2e.js
>      .expect(Selector(requestDemoModal.responseText).innerText).contains('\nThank you for the interest in AdTechMedia WordPress Plugin\nPlease check your inbox to schedule your demo.\n');
got it, thank you.
Fixed.

2017-07-31 11:54 UTC, grigoreme approved these changes

2017-07-31 11:55 UTC, merged